---
apiVersion: v1
kind: Service
metadata:
   name: demo-service
spec: 
  type: NodePort
  selector:
    app: train-schedule
  ports:
   - port: 8000
     targetPort: 8080
     nodePort: 30000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: train-schedule
  template: 
    metadata: 
      labels: 
        app: train-schedule
    spec:
     containers:
      - name: train-schedule
        image: sk260/edureka-project2:latest
        imagePullPolicy: Always 
        ports: 
         - containerPort: 8080
